### PR TITLE
Handle the re-connection of the devices after a power cycle

### PR DESCRIPTION
**Pull request by thibaulf**

### CODE REVIEW

**Comment by thenewwazoo** [comment]
Thank you for the PR! Have you been able to test this and observe that it resolves the issue?

**Comment by thibaulf** [comment]
I 've done many power cycle on the lutron bridge (20-25), it reconnects all the time

**Comment by thibaulf** [comment]
@thenewwazoo : I will post a new version of this PR that take care of the other corner cases. A PR on lutron-leap will also be required to support this upcoming version.

**Review by donavanbecker — APPROVED** [review]

**Comment by thenewwazoo** [comment]
@thibaulf thank you so much for getting this fixed! I'm sorry I've been so swamped and unable to be responsive. I've merged this change and am currently trying to figure out why it's not building. As soon as I figure this out, I'll get it published. Since @donavanbecker gave it the 👍, I'm going to skip beta tagging it and ship it straight to production.

**Pull request merged**
