### PR TITLE
Add message for natively supported device types

### PR DESCRIPTION
**Pull request by emroch**
I was surprised when I saw the log messages start coming in on first setup with a bunch of "not yet supported, skipping setup". I quickly realized that these devices were the actual switches I have paired to the Caseta bridge, but the message didn't sit right.

Since these devices are intentionally unsupported, I think it makes sense to give them their own message. It also tells the user "don't worry, this is normal".

While I was at it, I added an explicit case to the "not supported" category for the occupancy sensor, since I have the device name in the log. I may come back and add proper support for it since I have one, but I'm not a typescript developer so we'll see 😛

### CODE REVIEW

**Comment by thenewwazoo** [comment]
Is the list of "natively supported" devices exhaustive?

**Comment by emroch** [comment]
Probably not, these are just the ones I have available. I imagine the repeater would show up differently as would the plug-in dimmer and outdoor plug.

The ELV+ dimmer showed up the same as the regular Wall Dimmer, so I imagine the Caseta Pro variants of the in-wall devices will appear the same as well.

**Comment by thenewwazoo** [comment]
I'm probably crazy overthinking this, but I feel like non-exhaustively special-casing the natively-supported devices, and yet having anything unknown default to the "not yet" message is ... not quite right. I think maybe three separate messages is best:
* not yet supported because I don't have the hardware (or nobody who does has done it)
* natively supported
* not natively supported but no plans to add support / unknown?

**Comment by emroch** [comment]
Yeah, I think having a third message might be useful, though "unknown" is probably better than "no plans". Do you have anything in mind that is neither natively supported nor planned to be supported once someone has the hardware?

I'd say the following categories would work:
- Natively supported: in wall switches, bridges, etc
- Not yet supported: remotes/other devices not normally exposed to HomeKit that have known device types
- Unknown: basically just the default case, any device type we haven't seen before and thus don't know if it's natively supported or not yet supported. 

If you have something that you know about and never intend to support, a fourth "not to be supported" message could be added.

**Comment by thenewwazoo** [comment]
that sgtm

**Pull request merged**
