### PR TITLE
add remote support

### PR DESCRIPTION
**Pull request by donavanbecker**
- This is just the start for adding remote support to this plugin.
- My ultimate goal is to know when the remote is clicked so that you can create an automation and can link the remote with other devices that are not Lutron through the home app.
- Any help you can give by helping me understand the info that this plugin pulls to match up remote support.

### CODE REVIEW

**Comment by thenewwazoo** [comment]
Hi @donavanbecker, I'm about to release a beta version of the plugin to add support for the Pico remotes. Let me know if you get a chance to test it; I'd love some early feedback.

**Comment by donavanbecker** [comment]
@thenewwazoo I just saw that! I will test it out and let you know.

**Comment by donavanbecker** [comment]
@thenewwazoo, having issues with getting the cert, I have an m1 Mac so don't know why its not working....

**Comment by thenewwazoo** [comment]
The auth hasn’t changed so you shouldn’t need to change the keys, in case it’s already set up. Otherwise I’ll have to take a look tonight. I don’t have any immediate plans to port that functionality.

**Comment by donavanbecker** [comment]
> The auth hasn’t changed so you shouldn’t need to change the keys, in case it’s already set up. Otherwise I’ll have to take a look tonight. I don’t have any immediate plans to port that functionality. 

Yeah I had no use for the plugin, till now, so I removed the key, cert, etc. so don't have it any more.

**Comment by thenewwazoo** [comment]
Hm. [You're not the only one](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/3) having problems w/ the pylutron-caseta script. As I mentioned [over there](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/3#issuecomment-1003853010), the actual script itself differs from my instructions slightly. Can you try those?

**Comment by donavanbecker** [comment]
@thenewwazoo remotes work perfectly! Was able to get the info I needed with a raspberrypi

**Comment by thenewwazoo** [comment]
Killer - was it the OpenSSL spec that did the trick? I'd like to update the docs (I can't repro locally, sadly)

**Comment by donavanbecker** [comment]
> Killer - was it the OpenSSL spec that did the trick? I'd like to update the docs (I can't repro locally, sadly)

the last command I remember was `pip install pyOpenSSL`

once I did that, it worked.

**Pull request closed without merging**
